window.UPS_DATA = {
  "spec": {
    "va": 5000,
    "watts": 4000,
    "batteryWh": 2880,
    "pf": 0.8,
    "battery": "48 x 12 V x 5 Ah KSTAR 6-FM-5T"
  },
  "devices": [
    {
      "id": "L7-1",
      "floor": 7,
      "n": 1,
      "name": "Room Turag TV (55 inch)",
      "ups": 1,
      "w": 93,
      "mode": "need",
      "x": 25.0,
      "y": 72.3158
    },
    {
      "id": "L7-2",
      "floor": 7,
      "n": 2,
      "name": "Ad TV (55 inch)",
      "ups": 1,
      "w": 93,
      "mode": "need",
      "x": 46.655,
      "y": 61.7158
    },
    {
      "id": "L7-3",
      "floor": 7,
      "n": 3,
      "name": "Room Chitra VC + Docking",
      "ups": 1,
      "w": 186,
      "mode": "always",
      "x": 60.06,
      "y": 75.7368
    },
    {
      "id": "L7-4",
      "floor": 7,
      "n": 4,
      "name": "Room Chitra TV 1 (55 inch)",
      "ups": 1,
      "w": 93,
      "mode": "need",
      "x": 66.64,
      "y": 74.2316
    },
    {
      "id": "L7-5",
      "floor": 7,
      "n": 5,
      "name": "Room Chitra TV 2 (55 inch)",
      "ups": 1,
      "w": 93,
      "mode": "need",
      "x": 66.645,
      "y": 61.7053
    },
    {
      "id": "L7-6",
      "floor": 7,
      "n": 6,
      "name": "MFP (optional UPS use)",
      "ups": 1,
      "w": 1500,
      "mode": "optional",
      "x": 54.425,
      "y": 44.5579
    },
    {
      "id": "L7-7",
      "floor": 7,
      "n": 7,
      "name": "Vizoo zone (desktop, machines, Mac mini, 2 monitors)",
      "ups": 1,
      "w": 673,
      "mode": "need",
      "x": 53.4,
      "y": 33.0632
    },
    {
      "id": "L7-8",
      "floor": 7,
      "n": 8,
      "name": "Presentation TV (65 inch)",
      "ups": 1,
      "w": 110,
      "mode": "need",
      "x": 52.28,
      "y": 21.9474
    },
    {
      "id": "L7-9",
      "floor": 7,
      "n": 9,
      "name": "Ad TV (55 inch)",
      "ups": 1,
      "w": 93,
      "mode": "need",
      "x": 33.415,
      "y": 22.8421
    },
    {
      "id": "L7-10",
      "floor": 7,
      "n": 10,
      "name": "Level 7 Server Rack",
      "ups": 1,
      "w": 295,
      "mode": "always",
      "protected": true,
      "x": 41.48,
      "y": 10.2105
    },
    {
      "id": "L7-11",
      "floor": 7,
      "n": 11,
      "name": "Room Turag Docking System",
      "ups": 1,
      "w": 90,
      "mode": "always",
      "protected": false,
      "x": 28.55,
      "y": 65.3789
    },
    {
      "id": "L9-1",
      "floor": 9,
      "n": 1,
      "name": "ACU-3",
      "ups": 2,
      "w": 7.8,
      "mode": "always",
      "protected": true,
      "x": 19.085,
      "y": 75.2475
    },
    {
      "id": "L9-2",
      "floor": 9,
      "n": 2,
      "name": "TV of Room Meghna",
      "ups": 2,
      "w": 93,
      "mode": "need",
      "x": 26.485,
      "y": 82.6803
    },
    {
      "id": "L9-3",
      "floor": 9,
      "n": 3,
      "name": "Room Meghna VC + Docking",
      "ups": 2,
      "w": 186,
      "mode": "need",
      "x": 35.2,
      "y": 79.8444
    },
    {
      "id": "L9-4",
      "floor": 9,
      "n": 4,
      "name": "Level 9 Server Rack",
      "ups": 1,
      "w": 969,
      "mode": "always",
      "protected": true,
      "x": 67.545,
      "y": 79.8161
    },
    {
      "id": "L9-5",
      "floor": 9,
      "n": 5,
      "name": "ACU-1",
      "ups": 2,
      "w": 7.8,
      "mode": "always",
      "protected": true,
      "x": 76.365,
      "y": 76.2164
    },
    {
      "id": "L9-6",
      "floor": 9,
      "n": 6,
      "name": "TV of Room Teesta",
      "ups": 2,
      "w": 93,
      "mode": "need",
      "x": 81.075,
      "y": 83.4512
    },
    {
      "id": "L9-7",
      "floor": 9,
      "n": 7,
      "name": "Room Teesta VC + Docking",
      "ups": 2,
      "w": 90,
      "mode": "need",
      "x": 89.585,
      "y": 79.8798
    },
    {
      "id": "L9-8",
      "floor": 9,
      "n": 8,
      "name": "MFP (optional UPS use)",
      "ups": 2,
      "w": 1500,
      "mode": "optional",
      "x": 79.01,
      "y": 64.2928
    },
    {
      "id": "L9-9",
      "floor": 9,
      "n": 9,
      "name": "Level 9 Welcome TV / Apple TV",
      "ups": 2,
      "w": 2.5,
      "mode": "need",
      "x": 24.82,
      "y": 39.4696
    },
    {
      "id": "L9-R",
      "floor": 9,
      "n": "R",
      "name": "UPS-1 workbook residual: 43-inch TV + Poly camera VC system",
      "ups": 1,
      "w": 103,
      "mode": "need",
      "show": false,
      "x": 0,
      "y": 0
    },
    {
      "id": "L11-1",
      "floor": 11,
      "n": 1,
      "name": "Level 11 Server Rack",
      "ups": 2,
      "w": 370,
      "mode": "always",
      "protected": true,
      "x": 22.105,
      "y": 83.0764
    },
    {
      "id": "L11-2",
      "floor": 11,
      "n": 2,
      "name": "TV of Room Jamuna (65 inch)",
      "ups": 2,
      "w": 110,
      "mode": "need",
      "x": 31.405,
      "y": 77.6167
    },
    {
      "id": "L11-3",
      "floor": 11,
      "n": 3,
      "name": "Room Jamuna VC + Docking",
      "ups": 2,
      "w": 186,
      "mode": "need",
      "x": 36.25,
      "y": 81.7893
    },
    {
      "id": "L11-4",
      "floor": 11,
      "n": 4,
      "name": "TV of Room Padma (55 inch)",
      "ups": 2,
      "w": 67,
      "mode": "need",
      "x": 54.965,
      "y": 83.9109
    },
    {
      "id": "L11-5",
      "floor": 11,
      "n": 5,
      "name": "Room Padma VC + Docking",
      "ups": 2,
      "w": 186,
      "mode": "need",
      "x": 60.875,
      "y": 76.57
    },
    {
      "id": "L11-6",
      "floor": 11,
      "n": 6,
      "name": "TV of Room Buriganga",
      "ups": 2,
      "w": 67,
      "mode": "need",
      "x": 69.025,
      "y": 90.0283
    },
    {
      "id": "L11-7",
      "floor": 11,
      "n": 7,
      "name": "Room Buriganga VC + Docking",
      "ups": 2,
      "w": 186,
      "mode": "need",
      "x": 71.83,
      "y": 78.7977
    },
    {
      "id": "L11-8",
      "floor": 11,
      "n": 8,
      "name": "MFP (optional UPS use)",
      "ups": 2,
      "w": 1500,
      "mode": "optional",
      "x": 63.895,
      "y": 61.6478
    },
    {
      "id": "L11-9",
      "floor": 11,
      "n": 9,
      "name": "Level 11 Welcome TV / Apple TV",
      "ups": 2,
      "w": 143.5,
      "mode": "need",
      "x": 28.91,
      "y": 50.0283
    },
    {
      "id": "L11-10",
      "floor": 11,
      "n": 10,
      "name": "ACU-2",
      "ups": 2,
      "w": 7.8,
      "mode": "always",
      "protected": true,
      "x": 48.15,
      "y": 26.5347
    }
  ]
};
